# Generated by Django 4.2.30 on 2026-06-04 09:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_alter_classsubject_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ww_score', models.DecimalField(blank=True, decimal_places=2, help_text='Written Work score (0-100)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pt_score', models.DecimalField(blank=True, decimal_places=2, help_text='Performance Task score (0-100)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('qa_score', models.DecimalField(blank=True, decimal_places=2, help_text='Quarterly Assessment score (0-100)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('initial_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Weighted average before transmutation', max_digits=6, null=True)),
                ('transmuted_grade', models.PositiveSmallIntegerField(blank=True, help_text='Final grade after DepEd transmutation (60-100)', null=True, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('computed', 'Computed'), ('pending_approval', 'Pending Approval'), ('published', 'Published'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Teacher remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.classenrollment')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.classsubject')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.quarter')),
            ],
            options={
                'ordering': ['quarter', 'class_enrollment'],
                'unique_together': {('class_enrollment', 'class_subject', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='GradePublishEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('computed', 'Computed'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('published', 'Published'), ('unlocked', 'Unlocked'), ('edited', 'Edited')], max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for action (especially for unlock)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_actions', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_events', to='grading.grade')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
