# Generated by Django 4.2.30 on 2026-06-05 03:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_classsubject_teacher'),
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('core_value', models.CharField(choices=[('maka_diyos', 'Maka-Diyos'), ('makatao', 'Makatao'), ('makakalikasan', 'Makakalikasan'), ('makabansa', 'Makabansa')], max_length=20)),
                ('behavior', models.CharField(help_text="Specific behavior statement (e.g., 'Expresses one's spiritual beliefs')", max_length=255)),
                ('rating', models.CharField(choices=[('AO', 'Always Observed'), ('SO', 'Sometimes Observed'), ('RO', 'Rarely Observed'), ('NO', 'Not Observed')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_ratings', to='academics.classenrollment')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_ratings', to='academics.quarter')),
            ],
            options={
                'ordering': ['class_enrollment', 'quarter', 'core_value'],
                'unique_together': {('class_enrollment', 'quarter', 'core_value', 'behavior')},
            },
        ),
    ]
