# Generated by Django 4.2.30 on 2026-06-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_grade_review_comments'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conductrating',
            name='conduct_enroll_qtr_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='grade_status_quarter_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='grade_cs_qtr_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='grade_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='grade_updated_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='gradepublishevent',
            name='gpe_grade_action_created_idx',
        ),
        migrations.RenameIndex(
            model_name='gradepublishevent',
            new_name='grading_gra_grade_i_1408cf_idx',
            old_name='grading_gra_grade_i_idx',
        ),
        migrations.RenameIndex(
            model_name='gradepublishevent',
            new_name='grading_gra_action_56d32d_idx',
            old_name='grading_gra_action__idx',
        ),
        migrations.RenameIndex(
            model_name='gradereviewcomment',
            new_name='grading_gra_class_s_3068d5_idx',
            old_name='grading_gra_class_s_idx',
        ),
    ]
