# Generated by Django 4.2.30 on 2026-06-06 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0004_schedule_period_timetable'),
        ('grading', '0005_remove_conductrating_conduct_enroll_qtr_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('sf5', 'SF5 - Report Card'), ('sf10', 'SF10 - Form 137')], max_length=10)),
                ('school_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('signed', 'Signed'), ('printed', 'Printed')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional report data')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_report_cards', to=settings.AUTH_USER_MODEL)),
                ('quarter', models.ForeignKey(blank=True, help_text='Required for SF5, null for SF10', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cards', to='academics.quarter')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_report_cards', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['student', 'report_type', '-generated_at'], name='grading_rep_student_9b1f14_idx'), models.Index(fields=['school_year', 'quarter'], name='grading_rep_school__ea718a_idx'), models.Index(fields=['status'], name='grading_rep_status_a4aa28_idx')],
            },
        ),
    ]
