services:
  - type: web
    name: knhs-backend
    runtime: python
    region: singapore
    plan: free
    branch: main
    buildCommand: ./build.sh
    startCommand: daphne -b 0.0.0.0 -p $PORT config.asgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: RENDER
        value: true
      - key: CHANNEL_REDIS_URL
        fromService:
          type: redis
          name: knhs-redis
          property: connectionString

databases:
  - name: knhs-redis
    type: redis
    plan: free
    region: singapore
