# Generated by Django 4.2.30 on 2026-06-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_name',
            field=models.CharField(default='Kiwalan National High School', max_length=200),
        ),
    ]
