# Generated by Django 4.2.30 on 2026-06-06 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_rename_school_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="Unique identifier for this content block (e.g., 'home_hero_title')", max_length=100, unique=True)),
                ('title', models.CharField(help_text='Human-readable title for the content block', max_length=200)),
                ('section', models.CharField(choices=[('home_hero', 'Home - Hero Section'), ('home_about', 'Home - About Section'), ('home_features', 'Home - Features Section'), ('about_mission', 'About - Mission'), ('about_vision', 'About - Vision'), ('about_history', 'About - History'), ('academics_jhs', 'Academics - Junior High'), ('academics_shs', 'Academics - Senior High'), ('contact_info', 'Contact - Information'), ('contact_form', 'Contact - Form Instructions'), ('news_events', 'News & Events - Featured'), ('enrollment_info', 'Enrollment - Information'), ('footer', 'Footer')], help_text='Website section this block belongs to', max_length=50)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('html', 'HTML'), ('markdown', 'Markdown')], default='text', max_length=20)),
                ('content', models.TextField(help_text='Content of the block (text, HTML, or Markdown)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this block is currently active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section', 'key'],
                'indexes': [models.Index(fields=['section', 'is_active'], name='core_conten_section_1f8cff_idx'), models.Index(fields=['key'], name='core_conten_key_9c70d1_idx')],
            },
        ),
    ]
