# Generated by Django 4.2.30 on 2026-06-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assignment',
            name='assign_cs_due_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='assign_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='learningmaterial',
            name='material_cs_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='sub_assign_student_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='sub_submitted_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='sub_graded_at_idx',
        ),
    ]
