# Generated by Django 4.2.30 on 2026-06-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, help_text='M or F', max_length=1),
        ),
    ]
