# Generated by Django 4.2.30 on 2026-06-04 09:00

import apps.academics.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='e.g., SY 2024-2025', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False, help_text='Only one active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Einstein, Section A', max_length=100)),
                ('grade_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(12)])),
                ('section', models.CharField(blank=True, help_text='Optional section identifier', max_length=50)),
                ('strand', models.CharField(blank=True, choices=[('', 'None (JHS)'), ('STEM', 'Science, Technology, Engineering, and Mathematics'), ('ABM', 'Accountancy, Business, and Management'), ('HUMSS', 'Humanities and Social Sciences'), ('GAS', 'General Academic Strand'), ('TVL', 'Technical-Vocational-Livelihood')], help_text='Required for Grade 11-12', max_length=10)),
                ('join_code', models.CharField(default=apps.academics.models.generate_join_code, max_length=8, unique=True)),
                ('capacity', models.PositiveIntegerField(default=45, help_text='Maximum students')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academics.academicyear')),
                ('adviser', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['grade_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='e.g., ENG7, MATH10, GEN_MATH', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('grade_level', models.PositiveSmallIntegerField(help_text='7-10 for JHS, 11-12 for SHS', validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(12)])),
                ('strand', models.CharField(blank=True, choices=[('', 'None (JHS)'), ('STEM', 'Science, Technology, Engineering, and Mathematics'), ('ABM', 'Accountancy, Business, and Management'), ('HUMSS', 'Humanities and Social Sciences'), ('GAS', 'General Academic Strand'), ('TVL', 'Technical-Vocational-Livelihood')], help_text='Required for SHS specialized subjects', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['grade_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('name', models.CharField(help_text='e.g., First Quarter, Q1', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='academics.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ww_weight', models.DecimalField(decimal_places=2, default=30.0, help_text='Written Work weight (%)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pt_weight', models.DecimalField(decimal_places=2, default=50.0, help_text='Performance Task weight (%)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('qa_weight', models.DecimalField(decimal_places=2, default=20.0, help_text='Quarterly Assessment weight (%)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['classroom', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='active', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Transfer notes, special accommodations, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.classroom')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['classroom', 'student__profile__last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='academic_year_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='quarter',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='quarter_end_after_start'),
        ),
        migrations.AlterUniqueTogether(
            name='quarter',
            unique_together={('academic_year', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('classroom', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('academic_year', 'grade_level', 'section', 'strand')},
        ),
        migrations.AlterUniqueTogether(
            name='classenrollment',
            unique_together={('classroom', 'student')},
        ),
    ]
