# Generated by Django 4.2.30 on 2026-06-05 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_alter_classsubject_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('holiday', 'Holiday'), ('activity', 'School Activity'), ('deadline', 'Deadline'), ('exam', 'Examination'), ('meeting', 'Meeting'), ('other', 'Other')], default='other', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Optional for multi-day events', null=True)),
                ('is_school_wide', models.BooleanField(default=True, help_text='Visible to all users vs specific groups')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, help_text='Optional: Link to specific academic year', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='academics.academicyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'title'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='academics_s_start_d_2538a0_idx'), models.Index(fields=['event_type'], name='academics_s_event_t_7e43b9_idx')],
            },
        ),
    ]
