# Generated by Django 4.2.30 on 2026-06-05 23:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_schoolevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Period 1, Homeroom, Break', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Display order within the day')),
                ('is_break', models.BooleanField(default=False, help_text='True for recess/lunch breaks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academics.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'order', 'start_time'],
                'unique_together': {('academic_year', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('room', models.CharField(blank=True, help_text='Room/lab name or number', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.classsubject')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.classroom')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='academics.period')),
            ],
            options={
                'ordering': ['classroom', 'day_of_week', 'period__order'],
                'unique_together': {('classroom', 'period', 'day_of_week')},
            },
        ),
    ]
