# Generated by Django 4.2.30 on 2026-06-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='announcement',
            name='announce_pub_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='announce_aud_pub_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_user_read_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_type_created_idx',
        ),
    ]
