# Generated by Django 4.2.30 on 2026-06-05 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0003_remove_announcement_announce_pub_date_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_assignments', models.BooleanField(default=True)),
                ('email_grades', models.BooleanField(default=True)),
                ('email_announcements', models.BooleanField(default=True)),
                ('email_attendance', models.BooleanField(default=False)),
                ('email_materials', models.BooleanField(default=False)),
                ('inapp_assignments', models.BooleanField(default=True)),
                ('inapp_grades', models.BooleanField(default=True)),
                ('inapp_announcements', models.BooleanField(default=True)),
                ('inapp_attendance', models.BooleanField(default=True)),
                ('inapp_materials', models.BooleanField(default=True)),
                ('inapp_submissions', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preferences',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
