# Generated by Django 4.2.30 on 2026-06-06 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0005_messagethread_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_type', models.CharField(choices=[('academic', 'Academic Concern'), ('behavioral', 'Behavioral Issue'), ('personal', 'Personal Problem'), ('social', 'Social Issue'), ('family', 'Family Problem'), ('health', 'Health/Mental Health'), ('attendance', 'Attendance Issue'), ('disciplinary', 'Disciplinary Action'), ('referral', 'Referral'), ('other', 'Other')], max_length=20)),
                ('case_type_other', models.CharField(blank=True, help_text="Required if case_type is 'other'", max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('referred', 'Referred')], default='open', max_length=20)),
                ('referral_source', models.CharField(blank=True, help_text='Who referred this case', max_length=100)),
                ('referral_date', models.DateField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how the case was resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(blank=True, limit_choices_to={'role': 'guidance'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CounselingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('is_private', models.BooleanField(default=False, help_text='Private notes are only visible to guidance staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseling_notes', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='communications.counselingcase')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', '-created_at'], name='communicati_case_id_f311bb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='counselingcase',
            index=models.Index(fields=['student', 'status'], name='communicati_student_407234_idx'),
        ),
        migrations.AddIndex(
            model_name='counselingcase',
            index=models.Index(fields=['counselor', 'status'], name='communicati_counsel_c99cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='counselingcase',
            index=models.Index(fields=['case_type', 'status'], name='communicati_case_ty_52af40_idx'),
        ),
        migrations.AddIndex(
            model_name='counselingcase',
            index=models.Index(fields=['severity', 'status'], name='communicati_severit_2d1332_idx'),
        ),
    ]
