# Generated by Django 4.2.30 on 2026-06-05 00:16

import apps.enrollment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(db_index=True, default=apps.enrollment.models.generate_tracking_number, editable=False, max_length=20, unique=True)),
                ('applicant_data', models.JSONField(help_text='JSON data containing personal, contact, academic, guardian, and document info')),
                ('grade_level', models.CharField(choices=[('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=2)),
                ('strand', models.CharField(blank=True, choices=[('STEM', 'STEM - Science, Technology, Engineering, Mathematics'), ('ABM', 'ABM - Accountancy, Business, Management'), ('HUMSS', 'HUMSS - Humanities and Social Sciences'), ('GAS', 'GAS - General Academic Strand'), ('TVL', 'TVL - Technical-Vocational-Livelihood')], help_text='Required for Grade 11 and 12', max_length=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Needs Revision')], db_index=True, default='pending', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Notes from registrar/admin for the applicant')),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment Application',
                'verbose_name_plural': 'Enrollment Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='enrollment.enrollmentapplication')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='enrollmentapplication',
            index=models.Index(fields=['status', '-submitted_at'], name='enrollment__status_02095d_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentapplication',
            index=models.Index(fields=['grade_level', 'status'], name='enrollment__grade_l_db57c7_idx'),
        ),
    ]
